# Generated by Django 2.2.1 on 2019-05-09 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_auto_20190509_1207'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='datetime_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('user', 'property')},
        ),
    ]
