# Generated by Django 2.2.1 on 2019-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190510_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='datetime_stamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
