# Generated by Django 2.2.1 on 2019-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190510_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='datetime_stamp',
            field=models.DateTimeField(),
        ),
    ]
