# Generated by Django 2.2.1 on 2019-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190514_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profileimage/goat.jpg', upload_to='profileimage/'),
        ),
    ]
