# Generated by Django 2.2.1 on 2019-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_tag',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
