# Generated by Django 2.2.1 on 2019-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
