# Generated by Django 2.2.1 on 2019-05-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190508_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
