# Generated by Django 2.2.1 on 2019-05-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyZip',
            fields=[
                ('zip', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Iceland', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyType'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyZip'),
        ),
    ]
