# Generated by Django 2.2.1 on 2019-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190509_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='media/properties', verbose_name='Image'),
        ),
    ]
