# Generated by Django 2.2.1 on 2019-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190515_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
