# Generated by Django 2.2.1 on 2019-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20190515_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property/images', verbose_name='Image'),
        ),
    ]
